test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    exclude = ["install.nourl"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d653976.name = "Upgrade from 23.01"
