#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Reconfiguring congif file.."

old_app_url_domain="https://${old_domain}${old_path%/}"

pushd $install_dir
	yes | php$php_version artisan bookstack:update-url $old_app_url_domain https://${new_domain}${new_path}
popd

sed -i "/APP_URL=/c\APP_URL=https://${new_domain}${new_path}" $install_dir/.env

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
