#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

php_version=$(ynh_app_setting_get --key=php_version)
current_fpm_footprint=$(ynh_app_setting_get --key=fpm_footprint)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__maintenance_mode() {
    # Maintenance mode status
    if [ -f $install_dir/.maintenance ]
    then
        echo "1"
    else
        echo "0"
    fi
}

get__fpm_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        echo "specific"
    else
        echo "$current_fpm_footprint"
    fi
}

get__free_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        # If current_fpm_footprint is an integer, that's a numeric value for the footprint
        echo "$current_fpm_footprint"
    else
        echo "0"
    fi
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__maintenance_mode() {
    if [ "$maintenance_mode" -eq "1" ]; then
        # If maintenance_mode was set to 1, enable maintenance mode
        (cd "$install_dir" && ynh_exec_as_app \
            echo "Site under maintenance." > .maintenance)
        ynh_print_info "Maintenance mode disabled"
    elif [ "$maintenance_mode" -eq "0" ]; then
        # If maintenance_mode was set to 0, disable maintenance mode
        ynh_safe_rm $install_dir/.maintenance
        ynh_print_info "Maintenance mode enabled"
    fi
    ynh_app_setting_set --key=maintenance_mode --value="$maintenance_mode"
}

set__fpm_footprint() {
    if [ "$fpm_footprint" != "specific" ]
    then
        ynh_app_setting_set --key=fpm_footprint --value="$fpm_footprint"
    fi
}

set__fpm_free_footprint() {
    if [ "$fpm_footprint" = "specific" ]
    then
        ynh_app_setting_set --key=fpm_footprint --value="$fpm_free_footprint"
    fi
}

#=================================================

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "${changed[fpm_usage]}" == "true" ] || [ "${changed[fpm_footprint]}" == "true" ] || [ "${changed[fpm_free_footprint]}" == "true" ]; then
        # If fpm_footprint is set to 'specific', use $fpm_free_footprint value.
        if [ "$fpm_footprint" = "specific" ]
        then
            fpm_footprint=$fpm_free_footprint
        fi

        if [ "$fpm_footprint" == "0" ]
        then
            ynh_print_warn "When selecting 'specific', you have to set a footprint value into the field below."

            exit 0
        fi
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_config_add_phpfpm
}

ynh_app_config_run $1
