#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone="$(cat /etc/timezone)"
redis_db=$(ynh_redis_get_free_db)
email=$(ynh_user_get_info --username=$admin --key=mail)

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_memory_limit --value=256M
ynh_app_setting_set --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Create documentation/wiki content" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL BOOKSTACK WITH COMPOSER
#=================================================
ynh_script_progression "Installing $app with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=.env --destination=$install_dir/.env

#=================================================
# FINAL BOOKSTACK INSTALL
#=================================================
ynh_script_progression "Install $app"

pushd $install_dir
	php$php_version artisan key:generate --no-interaction --force
	php$php_version artisan migrate --no-interaction --force
	php$php_version artisan bookstack:create-admin --email="$email" --name="$admin" --external-auth-id="$admin"
popd

#=================================================
# SET PERMISSIONS
#=================================================

chmod -R 775 $install_dir/storage $install_dir/bootstrap/cache $install_dir/public/uploads
chown -R $app:www-data $install_dir/public/uploads && chmod -R 775 $install_dir/public/uploads

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
